<a href="https://colab.research.google.com/github/kotalaraghava/END-2.0---school-of-ai/blob/master/practice_simple_networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import make_regression

x,y = make_regression(n_samples=1000, n_features=10, n_informative=5, n_targets=3, 
                      random_state=2)

In [4]:
import torch

In [17]:
x = torch.tensor([[1,2,3,4]])
y = torch.tensor([[1,2,2,1]])

In [20]:
(x == y).sum()

tensor(2)

In [ ]:
x.shape, y.shape

((1000, 10), (1000, 3))

In [ ]:
type(x), x[0], y[0]

(numpy.ndarray,
 array([-0.99859353,  2.19284309, -0.42632569, -0.21043258, -1.13655612,
        -0.55671602, -0.63169045, -0.87625098, -0.99445578, -0.3677487 ]),
 array([-148.03723474,  -80.63209848,  -91.5736561 ]))

In [ ]:
inputs = []
outputs = []
for i in range(3,1000,2):
  i1, i2 = i, i*3
  inputs.append([i1,i2])
  outputs.append([i1+i2, i1*i2])

In [ ]:
inputs, outputs

In [ ]:
import numpy as np

In [ ]:
np.array(inputs)

In [ ]:
import torch

In [ ]:
X = torch.Tensor(inputs)
y = torch.Tensor(outputs)

In [ ]:
X.shape, y.shape

(torch.Size([499, 2]), torch.Size([499, 2]))

In [ ]:
class AddNetwork(torch.nn.Module):

  def __init__(self, input_dim=2, output_dim=2):
    super(AddNetwork, self).__init__()
    self.lin1 = torch.nn.Linear(input_dim, 12)
    self.lin2 = torch.nn.Linear(12, output_dim)

  def forward(self, x):
    x = self.lin1(x)
    x = torch.nn.functional.tanh(x)
    x = self.lin2(x)
    return x

In [ ]:
model = AddNetwork()
print(model)

AddNetwork(
  (lin1): Linear(in_features=2, out_features=12, bias=True)
  (lin2): Linear(in_features=12, out_features=2, bias=True)
)


In [ ]:
from torchsummary import summary

summary(model, (2,2))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                [-1, 2, 12]              36
            Linear-2                 [-1, 2, 2]              26
Total params: 62
Trainable params: 62
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1698: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


In [ ]:
loss_func = torch.nn.L1Loss()

optimizer = torch.optim.SGD(model.parameters(), lr=0.2, momentum=0.9)

In [ ]:

import torch
from torch.autograd import Variable

In [ ]:
epoches = 10
steps = X.size(0)

for i in range(epoches):
  for j in range(steps):
    # data_point = np.random.randint(X.size(0))
    x_var = Variable(X[j], requires_grad=True)
    y_var = Variable(y[j], requires_grad=True)
    
    optimizer.zero_grad()
    y_hat = model(x_var)
    print(y_hat, x_var, y_var)
    loss = loss_func.forward(y_hat, y_var)
    loss.backward()
    optimizer.step()
        
  if i % 50 == 0:
    print( "Epoch: {0}, Loss: {1}, ".format(i, loss.data.numpy()))



In [ ]:
model(torch.Tensor([[1,3], [4,5], [66,7]]))

/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1698: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


tensor([[  4002.3257, 357515.5938],
        [  4002.3315, 357516.3438],
        [  4002.3315, 357516.3438]], grad_fn=<AddmmBackward>)